import { ThemeTokens } from "@/lib/types/theme"

export const presetThemes: Record<string, ThemeTokens> = {
  minimal: {
    colors: {
      primary: "#09090b",
      primaryForeground: "#fafafa",
      secondary: "#f4f4f5",
      secondaryForeground: "#09090b",
      background: "#ffffff",
      foreground: "#09090b",
      muted: "#f4f4f5",
      mutedForeground: "#71717a",
      accent: "#8b5cf6",
      accentForeground: "#fafafa",
      destructive: "#ef4444",
      destructiveForeground: "#fafafa",
      border: "#e4e4e7",
      input: "#e4e4e7",
    },
    typography: {
      headingFont: "Inter",
      bodyFont: "Inter",
      scale: "md",
    },
    radius: 4,
    spacing: "cozy",
    shadows: "soft",
  },
  rounded: {
    colors: {
      primary: "#3b82f6",
      primaryForeground: "#ffffff",
      secondary: "#f1f5f9",
      secondaryForeground: "#0f172a",
      background: "#ffffff",
      foreground: "#0f172a",
      muted: "#f8fafc",
      mutedForeground: "#64748b",
      accent: "#8b5cf6",
      accentForeground: "#ffffff",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#e2e8f0",
      input: "#e2e8f0",
    },
    typography: {
      headingFont: "Inter",
      bodyFont: "Inter",
      scale: "md",
    },
    radius: 12,
    spacing: "cozy",
    shadows: "normal",
  },
  brutalist: {
    colors: {
      primary: "#000000",
      primaryForeground: "#ffffff",
      secondary: "#ffffff",
      secondaryForeground: "#000000",
      background: "#ffffff",
      foreground: "#000000",
      muted: "#f5f5f5",
      mutedForeground: "#737373",
      accent: "#000000",
      accentForeground: "#ffffff",
      destructive: "#dc2626",
      destructiveForeground: "#ffffff",
      border: "#000000",
      input: "#000000",
    },
    typography: {
      headingFont: "Inter",
      bodyFont: "Inter",
      scale: "lg",
    },
    radius: 0,
    spacing: "compact",
    shadows: "strong",
  },
  playful: {
    colors: {
      primary: "#ec4899",
      primaryForeground: "#ffffff",
      secondary: "#fce7f3",
      secondaryForeground: "#9f1239",
      background: "#fef3c7",
      foreground: "#78350f",
      muted: "#fef3c7",
      mutedForeground: "#92400e",
      accent: "#10b981",
      accentForeground: "#ffffff",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#fbbf24",
      input: "#fbbf24",
    },
    typography: {
      headingFont: "Poppins",
      bodyFont: "Poppins",
      scale: "md",
    },
    radius: 16,
    spacing: "spacious",
    shadows: "normal",
  },
  dark: {
    colors: {
      primary: "#ffffff",
      primaryForeground: "#09090b",
      secondary: "#27272a",
      secondaryForeground: "#fafafa",
      background: "#09090b",
      foreground: "#fafafa",
      muted: "#18181b",
      mutedForeground: "#a1a1aa",
      accent: "#8b5cf6",
      accentForeground: "#ffffff",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#27272a",
      input: "#27272a",
    },
    typography: {
      headingFont: "Inter",
      bodyFont: "Inter",
      scale: "md",
    },
    radius: 6,
    spacing: "cozy",
    shadows: "soft",
  },
  custom: {
    colors: {
      primary: "#6366f1",
      primaryForeground: "#ffffff",
      secondary: "#e0e7ff",
      secondaryForeground: "#312e81",
      background: "#ffffff",
      foreground: "#1e1b4b",
      muted: "#f5f3ff",
      mutedForeground: "#6b21a8",
      accent: "#8b5cf6",
      accentForeground: "#ffffff",
      destructive: "#ef4444",
      destructiveForeground: "#ffffff",
      border: "#c7d2fe",
      input: "#c7d2fe",
    },
    typography: {
      headingFont: "Inter",
      bodyFont: "Inter",
      scale: "md",
    },
    radius: 8,
    spacing: "cozy",
    shadows: "normal",
  },
}

export const themeLabels: Record<string, string> = {
  minimal: "Minimal Light",
  rounded: "Soft Rounded",
  brutalist: "Brutalist",
  playful: "Playful",
  dark: "Dark Minimal",
  custom: "Custom (from inspiration)",
}

export type ThemeKey = keyof typeof presetThemes

