import { Theme, ThemeTokens } from "./theme-types"

// Helper to create a theme object
function createTheme(
    id: string,
    name: string,
    aesthetic: Theme["aesthetic"],
    tokens: ThemeTokens
): Theme {
    return {
        id,
        name,
        aesthetic,
        tokens,
        preview: {
            swatches: [
                tokens.colors.primary,
                tokens.colors.secondary || tokens.colors.muted,
                tokens.colors.accent || tokens.colors.primary,
            ],
            sampleButtonStyle: {
                background: tokens.colors.primary,
                color: tokens.colors.primaryForeground || "#ffffff",
                borderRadius: `${tokens.radius}px`,
            },
        },
    }
}

// --- MINIMAL THEMES ---
export const minimalThemes: Theme[] = [
    createTheme("minimal-light", "Minimal Light", "minimal", {
        colors: {
            primary: "#09090b",
            primaryForeground: "#fafafa",
            secondary: "#f4f4f5",
            secondaryForeground: "#09090b",
            background: "#ffffff",
            foreground: "#09090b",
            muted: "#f4f4f5",
            mutedForeground: "#71717a",
            accent: "#f4f4f5",
            accentForeground: "#09090b",
            destructive: "#ef4444",
            destructiveForeground: "#fafafa",
            border: "#e4e4e7",
            input: "#e4e4e7",
        },
        typography: { headingFont: "Inter", bodyFont: "Inter", scale: "md" },
        radius: 4,
        spacing: "cozy",
        shadows: "soft",
    }),
    createTheme("minimal-gray", "Slate Minimal", "minimal", {
        colors: {
            primary: "#334155",
            primaryForeground: "#f8fafc",
            secondary: "#e2e8f0",
            secondaryForeground: "#0f172a",
            background: "#f8fafc",
            foreground: "#0f172a",
            muted: "#f1f5f9",
            mutedForeground: "#64748b",
            accent: "#e2e8f0",
            accentForeground: "#0f172a",
            border: "#cbd5e1",
            input: "#cbd5e1",
        },
        typography: { headingFont: "Inter", bodyFont: "Inter", scale: "md" },
        radius: 2,
        spacing: "cozy",
        shadows: "soft",
    }),
    createTheme("minimal-mono", "Monochrome", "minimal", {
        colors: {
            primary: "#000000",
            primaryForeground: "#ffffff",
            secondary: "#e5e5e5",
            secondaryForeground: "#000000",
            background: "#ffffff",
            foreground: "#000000",
            muted: "#f5f5f5",
            mutedForeground: "#737373",
            accent: "#f5f5f5",
            accentForeground: "#000000",
            border: "#e5e5e5",
            input: "#e5e5e5",
        },
        typography: { headingFont: "Roboto", bodyFont: "Roboto", scale: "sm" },
        radius: 0,
        spacing: "compact",
        shadows: "soft",
    }),
]

// --- ROUNDED THEMES ---
export const roundedThemes: Theme[] = [
    createTheme("rounded-soft", "Soft Blue", "rounded", {
        colors: {
            primary: "#3b82f6",
            primaryForeground: "#ffffff",
            secondary: "#eff6ff",
            secondaryForeground: "#1e3a8a",
            background: "#ffffff",
            foreground: "#0f172a",
            muted: "#f1f5f9",
            mutedForeground: "#64748b",
            accent: "#eff6ff",
            accentForeground: "#1e3a8a",
            border: "#e2e8f0",
            input: "#e2e8f0",
        },
        typography: { headingFont: "Inter", bodyFont: "Inter", scale: "md" },
        radius: 12,
        spacing: "cozy",
        shadows: "normal",
    }),
    createTheme("rounded-purple", "Soft Purple", "rounded", {
        colors: {
            primary: "#8b5cf6",
            primaryForeground: "#ffffff",
            secondary: "#f5f3ff",
            secondaryForeground: "#4c1d95",
            background: "#ffffff",
            foreground: "#2e1065",
            muted: "#f3f4f6",
            mutedForeground: "#6b7280",
            accent: "#f5f3ff",
            accentForeground: "#4c1d95",
            border: "#e5e7eb",
            input: "#e5e7eb",
        },
        typography: { headingFont: "Nunito", bodyFont: "Nunito", scale: "md" },
        radius: 16,
        spacing: "spacious",
        shadows: "normal",
    }),
    createTheme("rounded-peach", "Peach Fuzz", "rounded", {
        colors: {
            primary: "#f43f5e",
            primaryForeground: "#ffffff",
            secondary: "#fff1f2",
            secondaryForeground: "#881337",
            background: "#fff1f2",
            foreground: "#881337",
            muted: "#ffe4e6",
            mutedForeground: "#9f1239",
            accent: "#ffe4e6",
            accentForeground: "#881337",
            border: "#fecdd3",
            input: "#fecdd3",
        },
        typography: { headingFont: "Quicksand", bodyFont: "Quicksand", scale: "md" },
        radius: 20,
        spacing: "spacious",
        shadows: "soft",
    }),
]

// --- PLAYFUL THEMES ---
export const playfulThemes: Theme[] = [
    createTheme("playful-candy", "Candy Pop", "playful", {
        colors: {
            primary: "#ec4899",
            primaryForeground: "#ffffff",
            secondary: "#fce7f3",
            secondaryForeground: "#9f1239",
            background: "#fffbeb",
            foreground: "#78350f",
            muted: "#fef3c7",
            mutedForeground: "#92400e",
            accent: "#10b981",
            accentForeground: "#ffffff",
            border: "#fbbf24",
            input: "#fbbf24",
        },
        typography: { headingFont: "Poppins", bodyFont: "Poppins", scale: "md" },
        radius: 16,
        spacing: "spacious",
        shadows: "normal",
    }),
    createTheme("playful-mint", "Fresh Mint", "playful", {
        colors: {
            primary: "#059669",
            primaryForeground: "#ffffff",
            secondary: "#d1fae5",
            secondaryForeground: "#064e3b",
            background: "#ecfdf5",
            foreground: "#064e3b",
            muted: "#d1fae5",
            mutedForeground: "#047857",
            accent: "#34d399",
            accentForeground: "#ffffff",
            border: "#6ee7b7",
            input: "#6ee7b7",
        },
        typography: { headingFont: "Fredoka", bodyFont: "Open Sans", scale: "md" },
        radius: 12,
        spacing: "cozy",
        shadows: "soft",
    }),
    createTheme("playful-sun", "Sunshine", "playful", {
        colors: {
            primary: "#f59e0b",
            primaryForeground: "#ffffff",
            secondary: "#fef3c7",
            secondaryForeground: "#78350f",
            background: "#fffbeb",
            foreground: "#78350f",
            muted: "#fde68a",
            mutedForeground: "#92400e",
            accent: "#fbbf24",
            accentForeground: "#78350f",
            border: "#fcd34d",
            input: "#fcd34d",
        },
        typography: { headingFont: "Comic Neue", bodyFont: "Open Sans", scale: "lg" },
        radius: 18,
        spacing: "spacious",
        shadows: "normal",
    }),
]

// --- BRUTALIST THEMES ---
export const brutalistThemes: Theme[] = [
    createTheme("brutalist-bw", "Stark B&W", "brutalist", {
        colors: {
            primary: "#000000",
            primaryForeground: "#ffffff",
            secondary: "#ffffff",
            secondaryForeground: "#000000",
            background: "#ffffff",
            foreground: "#000000",
            muted: "#e5e5e5",
            mutedForeground: "#000000",
            accent: "#000000",
            accentForeground: "#ffffff",
            border: "#000000",
            input: "#000000",
        },
        typography: { headingFont: "Space Mono", bodyFont: "Space Mono", scale: "lg" },
        radius: 0,
        spacing: "compact",
        shadows: "strong",
    }),
    createTheme("brutalist-neo", "Neo Brutalism", "brutalist", {
        colors: {
            primary: "#8b5cf6",
            primaryForeground: "#ffffff",
            secondary: "#c4b5fd",
            secondaryForeground: "#000000",
            background: "#ede9fe",
            foreground: "#000000",
            muted: "#ddd6fe",
            mutedForeground: "#000000",
            accent: "#a78bfa",
            accentForeground: "#000000",
            border: "#000000",
            input: "#000000",
        },
        typography: { headingFont: "Archivo Black", bodyFont: "Inter", scale: "lg" },
        radius: 4,
        spacing: "cozy",
        shadows: "strong",
    }),
    createTheme("brutalist-yellow", "Construction", "brutalist", {
        colors: {
            primary: "#000000",
            primaryForeground: "#facc15",
            secondary: "#facc15",
            secondaryForeground: "#000000",
            background: "#fefce8",
            foreground: "#000000",
            muted: "#fef08a",
            mutedForeground: "#000000",
            accent: "#fde047",
            accentForeground: "#000000",
            border: "#000000",
            input: "#000000",
        },
        typography: { headingFont: "Chivo Mono", bodyFont: "Chivo Mono", scale: "lg" },
        radius: 0,
        spacing: "compact",
        shadows: "strong",
    }),
]

// --- TECH THEMES ---
export const techThemes: Theme[] = [
    createTheme("tech-cyber", "Cyberpunk", "tech", {
        colors: {
            primary: "#0ea5e9",
            primaryForeground: "#ffffff",
            secondary: "#0f172a",
            secondaryForeground: "#38bdf8",
            background: "#020617",
            foreground: "#e2e8f0",
            muted: "#1e293b",
            mutedForeground: "#94a3b8",
            accent: "#d946ef",
            accentForeground: "#ffffff",
            border: "#1e293b",
            input: "#1e293b",
        },
        typography: { headingFont: "Orbitron", bodyFont: "Rajdhani", scale: "md" },
        radius: 2,
        spacing: "cozy",
        shadows: "strong",
    }),
    createTheme("tech-matrix", "Matrix", "tech", {
        colors: {
            primary: "#22c55e",
            primaryForeground: "#000000",
            secondary: "#052e16",
            secondaryForeground: "#4ade80",
            background: "#020617",
            foreground: "#4ade80",
            muted: "#064e3b",
            mutedForeground: "#22c55e",
            accent: "#166534",
            accentForeground: "#ffffff",
            border: "#14532d",
            input: "#14532d",
        },
        typography: { headingFont: "Share Tech Mono", bodyFont: "Share Tech Mono", scale: "sm" },
        radius: 0,
        spacing: "compact",
        shadows: "soft",
    }),
    createTheme("tech-slate", "Clean Tech", "tech", {
        colors: {
            primary: "#6366f1",
            primaryForeground: "#ffffff",
            secondary: "#1e293b",
            secondaryForeground: "#e2e8f0",
            background: "#0f172a",
            foreground: "#f8fafc",
            muted: "#334155",
            mutedForeground: "#94a3b8",
            accent: "#4f46e5",
            accentForeground: "#ffffff",
            border: "#334155",
            input: "#334155",
        },
        typography: { headingFont: "Inter", bodyFont: "Inter", scale: "md" },
        radius: 6,
        spacing: "cozy",
        shadows: "soft",
    }),
]

// --- WARM THEMES ---
export const warmThemes: Theme[] = [
    createTheme("warm-earth", "Earthen", "warm", {
        colors: {
            primary: "#78350f",
            primaryForeground: "#fffbeb",
            secondary: "#fffbeb",
            secondaryForeground: "#78350f",
            background: "#fff7ed",
            foreground: "#431407",
            muted: "#ffedd5",
            mutedForeground: "#9a3412",
            accent: "#fdba74",
            accentForeground: "#431407",
            border: "#fed7aa",
            input: "#fed7aa",
        },
        typography: { headingFont: "Merriweather", bodyFont: "Lato", scale: "md" },
        radius: 8,
        spacing: "cozy",
        shadows: "soft",
    }),
    createTheme("warm-coffee", "Coffee House", "warm", {
        colors: {
            primary: "#3f2e3e",
            primaryForeground: "#efebe9",
            secondary: "#efebe9",
            secondaryForeground: "#3e2723",
            background: "#d7ccc8",
            foreground: "#3e2723",
            muted: "#a1887f",
            mutedForeground: "#3e2723",
            accent: "#8d6e63",
            accentForeground: "#efebe9",
            border: "#bcaaa4",
            input: "#bcaaa4",
        },
        typography: { headingFont: "Playfair Display", bodyFont: "Source Sans Pro", scale: "md" },
        radius: 6,
        spacing: "cozy",
        shadows: "soft",
    }),
    createTheme("warm-sunset", "Sunset", "warm", {
        colors: {
            primary: "#ea580c",
            primaryForeground: "#ffffff",
            secondary: "#ffedd5",
            secondaryForeground: "#9a3412",
            background: "#fff7ed",
            foreground: "#7c2d12",
            muted: "#fed7aa",
            mutedForeground: "#c2410c",
            accent: "#fb923c",
            accentForeground: "#ffffff",
            border: "#fdba74",
            input: "#fdba74",
        },
        typography: { headingFont: "Lora", bodyFont: "Open Sans", scale: "md" },
        radius: 12,
        spacing: "spacious",
        shadows: "soft",
    }),
]

// --- DARK THEMES ---
export const darkThemes: Theme[] = [
    createTheme("dark-night", "Midnight", "dark", {
        colors: {
            primary: "#ffffff",
            primaryForeground: "#09090b",
            secondary: "#27272a",
            secondaryForeground: "#fafafa",
            background: "#09090b",
            foreground: "#fafafa",
            muted: "#18181b",
            mutedForeground: "#a1a1aa",
            accent: "#8b5cf6",
            accentForeground: "#ffffff",
            border: "#27272a",
            input: "#27272a",
        },
        typography: { headingFont: "Inter", bodyFont: "Inter", scale: "md" },
        radius: 6,
        spacing: "cozy",
        shadows: "soft",
    }),
    createTheme("dark-obsidian", "Obsidian", "dark", {
        colors: {
            primary: "#6366f1",
            primaryForeground: "#ffffff",
            secondary: "#1e1b4b",
            secondaryForeground: "#c7d2fe",
            background: "#020617",
            foreground: "#e2e8f0",
            muted: "#1e293b",
            mutedForeground: "#94a3b8",
            accent: "#4f46e5",
            accentForeground: "#ffffff",
            border: "#1e293b",
            input: "#1e293b",
        },
        typography: { headingFont: "Inter", bodyFont: "Inter", scale: "md" },
        radius: 8,
        spacing: "cozy",
        shadows: "strong",
    }),
    createTheme("dark-navy", "Deep Navy", "dark", {
        colors: {
            primary: "#38bdf8",
            primaryForeground: "#0f172a",
            secondary: "#1e293b",
            secondaryForeground: "#e2e8f0",
            background: "#0f172a",
            foreground: "#f1f5f9",
            muted: "#334155",
            mutedForeground: "#94a3b8",
            accent: "#0ea5e9",
            accentForeground: "#ffffff",
            border: "#1e293b",
            input: "#1e293b",
        },
        typography: { headingFont: "Inter", bodyFont: "Inter", scale: "md" },
        radius: 4,
        spacing: "cozy",
        shadows: "normal",
    }),
]

// Map all themes by ID for easy lookup
export const presetThemes: Record<string, Theme> = {
    ...minimalThemes.reduce((acc, t) => ({ ...acc, [t.id]: t }), {}),
    ...roundedThemes.reduce((acc, t) => ({ ...acc, [t.id]: t }), {}),
    ...playfulThemes.reduce((acc, t) => ({ ...acc, [t.id]: t }), {}),
    ...brutalistThemes.reduce((acc, t) => ({ ...acc, [t.id]: t }), {}),
    ...techThemes.reduce((acc, t) => ({ ...acc, [t.id]: t }), {}),
    ...warmThemes.reduce((acc, t) => ({ ...acc, [t.id]: t }), {}),
    ...darkThemes.reduce((acc, t) => ({ ...acc, [t.id]: t }), {}),
}
